backend:
  name: github
  repo: TeD-CHub/The-Functional-Fork
  branch: main
  auth_endpoint: https://functional-fork-cms-auth.vercel.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

site_url: "https://the-functional-fork.vercel.app/"
logo_url: "https://the-functional-fork.vercel.app/images/logo.jpeg"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "SEO Title", name: "seo_title", widget: "string", required: false }
      - { label: "SEO Description", name: "seo_description", widget: "text", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

